### ISSUE TITLE
大神 付款成功 无法发卡是怎么回事 自动发卡空白

### ISSUE THREAD

**Issue by zjjhqwqc** [szvone/vfkphp#4]
大神 付款成功 无法发卡是怎么回事 自动发卡空白 @szvone

**Comment by ouliblog** [comment]
改一下代码就可以用，你可以看一下我的网站[http://faka.ouliweb.cn/](http://faka.ouliweb.cn/)

**Comment by szvone** [comment]
v1.2已修复
