### ISSUE TITLE
发卡就象发神经

### ISSUE THREAD

**Issue by year5601** [szvone/vfkphp#5]
支付都正常，卡密就象捉迷藏，有时能出来，有时为空白，而且大多数时候是空白。这代码够神经的，服了！

**Comment by ouliblog** [comment]
自己不会改一下吗？改一下就能用！

**Comment by Mrzzhi** [comment]
> 自己不会改一下吗？改一下就能用！

请教大佬如何改的。

**Comment by vcdlushan** [comment]
> > 自己不会改一下吗？改一下就能用！
> 
> 请教大佬如何改的。

你学会怎么修改了吗？

**Comment by Mrzzhi** [comment]
> > > 自己不会改一下吗？改一下就能用！
> > 
> > 
> > 请教大佬如何改的。
> 
> 你学会怎么修改了吗？



> > > 自己不会改一下吗？改一下就能用！
> > 
> > 
> > 请教大佬如何改的。
> 
> 你学会怎么修改了吗？

已经修改好了
