### ISSUE TITLE
感谢作者！已安装测试成功！

### ISSUE THREAD

**Issue by ouliblog** [szvone/vfkphp#6]
刚安装时也遇到了支付成功没有显示卡密的问题，后来研究了一下，改了几行代码就能用了，感兴趣的朋友可以访问一下我的网站
[http://faka.ouliweb.cn/](http://faka.ouliweb.cn/)

**Comment by zmy17624559888** [comment]
可以说一下修改思路吗？谢谢🙏

**Comment by szvone** [comment]
v1.2已修复
